
CREATE DATABASE mock_db_1M;

\c mock_db_1M;

CREATE TABLE mock_table (
    id integer PRIMARY KEY,
    trans_type varchar(255),
    sys_retailer_bu_name varchar(255),
    sys_retailer_bu_id varchar(255),
    sys_retailer_bt_bu_id varchar(255),
    sys_retailer_bt_bu_name varchar(255),
    sys_product_id varchar(255),
    arrangement_ext_id varchar(255),
    arrangement_name varchar(255),
    credit_memo_date varchar(255),
    data_source varchar(255),
    final_bt_primary_id varchar(255),
    final_bt_primary_id_type varchar(255),
    net_sales_amt varchar(255),
    gross_sales_amt varchar(255),
    final_dist_id varchar(255),
    final_dist_id_type varchar(255),
    final_dist_name varchar(255),
    final_item varchar(255),
    final_item_name varchar(255),
    final_item_type varchar(255),
    final_pg_alias varchar(255),
    final_qty varchar(255),
    final_sales_price varchar(255),
    final_st_primary_id varchar(255),
    final_st_primary_id_type varchar(255),
    final_uom varchar(255),
    final_wac varchar(255),
    inv_date varchar(255),
    inv_line varchar(255),
    inv_num varchar(255),
    order_type varchar(255),
    reason_code varchar(255),
    bill_type varchar(255)
);


INSERT INTO mock_table VALUES(generate_series(1,1000000),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text),
                                    md5(random()::text));